### ISSUE TITLE
connection not stable

### ISSUE THREAD

**Issue by fengxx** [nccgroup/SocksOverRDP#8] opened 2021-11-04 05:43 UTC
thanks for the tool, it is very useful, however running ssh over the socks created on rcp channel is not stable
* there is a lag for command typed and displayed.
* ssh connection aborts quite often

**Comment by earthquake** [comment] 2021-11-04 09:22
Hi @fengxx,

Thanks for the bug report, it seems that your connection to the RDP server is slow and that affecting the underlying virtual channel where the connection lags. Unfortunately this is not something that I can fix, because:
1. not much to do with the tool
2. there is no way I can reproduce it based on what you wrote

You can try recompiling the executable, by changing this this value to 6: 	running_args.priority = 4; (line 445)

This would prioritise the virtual channel giving it real time priority: "WTS_CHANNEL_OPTION_DYNAMIC_PRI_REAL
Real-time priority. Use this priority level only in cases where the data transfer is absolutely critical. The data transfer size should be limited to a few hundred bytes per message.".

**Comment by fengxx** [comment] 2021-11-10 06:18
I tried `WTS_CHANNEL_OPTION_DYNAMIC_PRI_REAL` but no luck. 
I guess it maybe related the behavior of ssh, which transfer every key stroke in a packet for interactive purpose, heavily affected by Nagle algorithm (default enabled in winsock) with 200-ms ACK delay. 
I also tried ssh's ProxyCommand  config with socat's nodelay
`ProxyCommand socat -b 4192 - "SOCKS5:%h:%p|TCP:127.0.0.1:1080,nodelay"` but no improvement

**Comment by earthquake** [comment] 2021-11-19 11:21
Sorry to hear that. Will close this for now, since it looks like a network issue rather than a problem with the code itself.

**Closed as completed by earthquake** 2021-11-19 11:21 UTC
